# Generated by Django 4.1.7 on 2023-05-09 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('hip', models.FloatField()),
                ('bust', models.FloatField()),
                ('waist', models.FloatField()),
                ('height', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_attributes',
            },
        ),
    ]
