# Generated by Django 4.1.7 on 2023-03-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitModel',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_display_name', models.CharField(default='Outfit#', max_length=255)),
                ('gender', models.CharField(max_length=100)),
                ('master_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('outfit_type', models.CharField(max_length=100)),
                ('base_colour', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('usage', models.CharField(max_length=100)),
                ('image_link', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
