# Generated by Django 4.1.7 on 2023-03-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app_1', '0002_outfitmodel_delete_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='outfitmodel',
            table='outfit_details',
        ),
    ]
