# Generated by Django 4.1.7 on 2023-03-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app_1', '0003_alter_outfitmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'user_images',
            },
        ),
        migrations.RenameModel(
            old_name='OutfitModel',
            new_name='Outfit',
        ),
    ]
