# Generated by Django 4.1.7 on 2023-03-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app_1', '0004_userimage_rename_outfitmodel_outfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='image_name',
            field=models.CharField(default='user_image', max_length=100),
        ),
    ]
