# Generated by Django 4.1.7 on 2023-03-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app_1', '0005_userimage_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='image_display_name',
            new_name='image_name',
        ),
        migrations.AddField(
            model_name='outfit',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
