export const POST_INITIAL_RECOMMEND_REQUEST = "POST_INITIAL_RECOMMEND_REQUEST";
export const POST_INITIAL_RECOMMEND_SUCCESS = "POST_INITIAL_RECOMMEND_SUCCESS";
export const POST_INITIAL_RECOMMEND_FAILURE = "POST_INITIAL_RECOMMEND_FAILURE";
