# Generated by Django 4.1.7 on 2023-03-03 00:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bust', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=4)),
                ('body_type', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
