# Generated by Django 4.1.7 on 2023-03-03 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 0, 55, 46, 949761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 0, 55, 46, 949902, tzinfo=datetime.timezone.utc)),
        ),
    ]
