# Generated by Django 4.1.7 on 2023-03-31 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app_2', '0004_image_alter_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 22, 0, 55, 460565, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 22, 0, 55, 460717, tzinfo=datetime.timezone.utc)),
        ),
    ]
