# Generated by Django 4.1.7 on 2023-04-04 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app_2', '0005_delete_image_alter_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 6, 35, 1, 179921, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 6, 35, 1, 179921, tzinfo=datetime.timezone.utc)),
        ),
    ]
