# Generated by Django 4.1.7 on 2023-04-13 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app_2', '0007_alter_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 23, 41, 52, 592724, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 23, 41, 52, 592908, tzinfo=datetime.timezone.utc)),
        ),
    ]
